# Generated by Django 4.1.5 on 2023-07-17 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_postpic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postpic',
            old_name='content',
            new_name='caption',
        ),
    ]
